config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :home_ingredients, only: [:destroy, :create, :new]
  resources :search, only: :index
  resources :receipts, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/home_ingredient.rb
class HomeIngredient < ApplicationRecord
	validates :name, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :receipt
end

app/models/receipt.rb
class Receipt < ApplicationRecord
	has_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/home_ingredients_displayable.rb
module HomeIngredientsDisplayable
  extend ActiveSupport::Concern

  included do
  	def load_home_ingredients
  		@home_ingredients = HomeIngredient.all
  	end
  end

  class_methods do

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home_ingredients = HomeIngredient.all
  end
end

app/controllers/home_ingredients_controller.rb
class HomeIngredientsController < ApplicationController
  def destroy
    @home_ingredient = HomeIngredient.find params[:id]
    @home_ingredient.destroy

    redirect_to root_path
  end

  def create
    @home_ingredient = HomeIngredient.create name: params[:home_ingredient][:name]

    redirect_to root_path
  end

  def new
    @home_ingredient = HomeIngredient.new
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def show
    @receipt = Receipt.find params[:id]

    respond_to do |format|
      format.html
      format.json { render json: @receipt }
     end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  include HomeIngredientsDisplayable

  before_action :load_home_ingredients

  def index
    @relevancy_params = { second_relevant: {cook_time: :asc}}
    @relevancy_params = @relevancy_params.merge(second_relevant: second_relevant_sort_params) if params[:second_relevant].present?

    @relevant_receipts = RelevantRecipes.new.call(@relevancy_params)

    @relevant_receipts = @relevant_receipts.page params[:page]
    respond_to do |format|
      format.html
      format.json { render json: @relevant_receipts }
     end
  end

  def second_relevant_sort_params
    params.permit(second_relevant: {}).to_h[:second_relevant]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
	def invert_search_direction(direction)
		if 'asc' == direction.to_s
			'desc'
		else
			'asc'
		end
	end

	def second_relevant_params(old_params, key)
		inverted_direction = invert_search_direction(old_params[:second_relevant][key])
		{ key => inverted_direction }
	end
end

app/views/home/index.html.slim
= render partial: 'home_ingredients/add_new_ingredient'

app/views/home_ingredients/_add_new_ingredient.html.slim
= turbo_frame_tag 'new_home_ingredient' do
  = link_to "Add new Home Ingredient", new_home_ingredient_path, class: 'btn  btn-sm'

app/views/home_ingredients/_content.html.slim
div class="container"
  table class="table table-sm table-striped table-hover" size="sm"
    thead
      tr
        th Home Ingredients
        th
    tbody
      = render @home_ingredients
  div class="container"
    = render partial: 'home_ingredients/add_new_ingredient'

app/views/home_ingredients/_home_ingredient.html.slim
tr
  td= home_ingredient.name
  td= link_to "Delete", home_ingredient_path(home_ingredient), data: { turbo_method: :delete }, class: 'btn btn-outline-danger btn-sm'

app/views/home_ingredients/new.html.slim
= turbo_frame_tag 'new_home_ingredient' do
  = form_with model: @home_ingredient, data: { turbo: :false } do |form|
    = form.label "Ingredient Name"
    = form.text_field :name
    = form.submit
  = link_to "Never Mind", root_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title RecipeAdvisor
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    div class="container"
      table class="table table-sm table-striped table-hover" size="sm"
        thead
          tr
            th Home Ingredients
            th
        tbody
          = render @home_ingredients
      div class="container"
        = turbo_frame_tag 'new_home_ingredient' do 
          - yield :new_home_ingredient 

app/views/layouts/receipts.html.slim
doctype html
html
  head
    title RecipeAdvisor
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    = yield

app/views/receipts/_receipt.html.slim
tr
  th= link_to receipt.title, receipt_path(receipt)
  th= receipt.cook_time
  th= receipt.prep_time
  th= receipt.rating
  th= receipt.cuisine
  th= number_to_percentage(receipt.relevancy * 100, precision: 2)
  th
		img src="#{receipt.image}" width=50

app/views/receipts/show.html.slim
div class="container"
  table class="table table-sm table-striped table-hover" size="sm"
    tbody
      tr
        td Title
        td= @receipt.title
      tr
        td Cook time
        td= @receipt.cook_time
      tr
        td Preparation time
        td= @receipt.prep_time
      tr
        td Rating
        td= @receipt.rating
      tr
        td Cuisine
        td= @receipt.cuisine
      tr
        td Author
        td= @receipt.author
      tr
        td Category
        td= @receipt.category
	img src="#{@receipt.image}" width=50
  table class="table table-sm table-striped table-hover" size="sm"
    thead
      tr
        th Ingredients & Receipt
    tbody
      - @receipt.ingredients.each do |ingredient|
        tr
          td= ingredient.name

app/views/search/_content.html.slim
td= link_to "Search Recipes", search_index_path, class: 'btn btn-outline-danger btn-sm'
= turbo_frame_tag 'search_results'
  - if @relevant_receipts
    div class="container"
      table class="table table-sm table-striped table-hover" size="sm"
        thead
          tr
            th Receipts
            th
              =link_to "Cook Time", search_index_path( second_relevant: second_relevant_params(@relevancy_params, :cook_time))
            th
              =link_to "Prep Time", search_index_path( second_relevant: {prep_time: :asc}.merge(second_relevant_params(@relevancy_params, :prep_time)))
            th Rating
            th Cuisine
            th Relevancy Score
            th
        tbody
          - @relevant_receipts.each do |receipt|
            = render partial: receipt
    = paginate @relevant_receipts, params: @relevancy_params

app/views/search/index.html.slim
= render partial: 'content'